<a href="https://colab.research.google.com/github/cyan9212/wikibooks-python_ml_guide/blob/main/01_pandas%26numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.array([1,2,3])
print(type(arr1))

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int = array_float.astype('int32')
print(array_int, array_int.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

seq_array = np.arange(1,10)
print(seq_array)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array, zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array, one_array.dtype, one_array.shape)

<class 'numpy.ndarray'>
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32
[1 2 3 4 5 6 7 8 9]
[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


In [ ]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array4 = array1.reshape(-1,5)
print('array4 shape:\n',array4.shape)

array5 = array1.reshape(5,-1)
print('array5 shape:\n',array5.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4 shape:
 (2, 5)
array5 shape:
 (5, 2)


In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3 dimension -> 2 dimension
array2 = array3d.reshape(-1,1)
print('array2:\n', array2.tolist())
print('array2 shape:', array2.shape)

#1 dimension -> 2 dimension
array3 = array1.reshape(-1,1)
print('array3:\n', array3.tolist())
print('array3 shape:\n', array3.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array2:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array2 shape: (8, 1)
array3:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array3 shape:
 (8, 1)


In [ ]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print(value, type(value))
print(array1[-1],array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
3 <class 'numpy.int64'>
9 8


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0,1])
print(array2d[1,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
4


In [ ]:
#Fancy Indexing
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2]:',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2]:',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]:', array5.tolist())

array2d[[0,1],2]: [3, 6]
array2d[[0,1],0:2]: [[1, 2], [4, 5]]
array2d[[0,1]]: [[1, 2, 3], [4, 5, 6]]


In [ ]:
#Boolean Indexing
array1d = np.arange(1,10)
array2 = array1d[array1d >5]
print(array2)
array1d > 5
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]
[6 7 8 9]


In [ ]:
#sort()
org_array  = np.array([3,1,9,5])
print('raw array:',org_array)

sorted_array = np.sort(org_array)
print('sorted array:',sorted_array)

sorted_array_desc = np.sort(org_array)[::-1]
print('descending sort:',sorted_array_desc)

array2d = np.array([[8,12],[7,1]])

sorted_array2d_axis0 = np.sort(array2d, axis=0)
print('row direction sort\n', sorted_array2d_axis0)

sorted_array2d_axis1 = np.sort(array2d, axis=1)
print('col direction sort\n',sorted_array2d_axis1)

raw array: [3 1 9 5]
sorted array: [1 3 5 9]
descending sort: [9 5 3 1]
row direction sort
 [[ 7  1]
 [ 8 12]]
col direction sort
 [[ 8 12]
 [ 1  7]]


In [ ]:
#arg_sort()
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('정렬 후 원본 행렬의 인덱스:',sort_indices)

org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('내림차순 정렬 후 원본 행렬의 인덱스:',sort_indices_desc)

name = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices = np.argsort(score_array)
print('arg_index:',sort_indices)
print('name:',name[sort_indices])

<class 'numpy.ndarray'>
정렬 후 원본 행렬의 인덱스: [1 0 3 2]
내림차순 정렬 후 원본 행렬의 인덱스: [2 3 0 1]
arg_index: [0 2 4 1 3]
name: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [ ]:
#행렬의 내적
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과\n',dot_product)

#전치행렬
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬\n', transpose_mat)

행렬 내적 결과
 [[ 58  64]
 [139 154]]
A의 전치행렬
 [[1 3]
 [2 4]]
